name: Test
on: [push]
env:
  SECRETS_CONTEXT: ${{ toJson(secrets) }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Airflow DAGs Test
      uses: TalkWIthKeyboard/airflow-dags-test-action@v1.0
      with:
        requirements-file: requirements.txt
        dags-path: dags
        dags-test-folder: tests/dags
